version: 2
jobs:
    # The build job
    build:
        working_directory: ~/cidemo
        docker:
            - image: circleci/node:6.10-browsers
        steps:
            # Install project dependencies
            - run:
                name: Install local dependencies
                command: npm install
            # Lint the source code
            - run:
                name: Linting
                command: npm run lint
            # Test the source code
            - run:
                name: Testing
                command: npm run test
- dist