version: 2
jobs:
    # The build job
    build:
        working_directory: ~/cidemo
        docker:
            - image: circleci/node:6.10-browsers
        steps:
            # Install project dependencies
            - run:
                name: Install local dependencies
                command: npm install
            # ng serve the source code
            - run:
                name: Ng Serve
                command: ng serve
            # ng build the source code
            - run:
                name: Ng Build
                command: ng build
            # Lint the source code
            - run:
                name: Linting
                command: ng lint
            # Test the source code
            - run:
                name: Testing
                command: ng test
- dist